/**
 * Regenerate the vendored model catalogue from models.dev.
 *
 *   npx tsx scripts/sync-model-catalog.ts
 *
 * Writes src/lib/models/catalog.generated.ts. Run it when providers ship new
 * models; the output is committed so a build never depends on models.dev being
 * up, and a settings page never shows a spinner because someone else's CDN is
 * having a bad day.
 *
 * ── Why vendor at all ───────────────────────────────────────────────────────
 *
 * The full catalogue is 193 providers and ~7,250 models — 4.2 MB, which is not
 * something to ship to a browser. Trimmed to the providers OpenMind can
 * actually call, and to the fields a picker needs, it is ~86 KB raw and ~13 KB
 * gzipped. That fits.
 *
 * ── What this is NOT ────────────────────────────────────────────────────────
 *
 * It is what EXISTS, not what a given customer can reach. A real Groq key
 * tested against this catalogue reached 13 models, and the default OpenMind had
 * hard-coded was not one of them. Per-key discovery answers that half; see
 * `GET /v1/models` in the vault-keys Edge Function. The catalogue supplies the
 * metadata — pricing, context window, capabilities — that no /v1/models
 * response carries.
 */

import { writeFileSync } from 'node:fs'
import { CATALOG_PROVIDERS } from '../src/lib/models/providers'

const SOURCE = 'https://models.dev/api.json'
const OUT = 'src/lib/models/catalog.generated.ts'

interface UpstreamModel {
  id?: string
  name?: string
  reasoning?: boolean
  tool_call?: boolean
  release_date?: string
  modalities?: { input?: string[]; output?: string[] }
  limit?: { context?: number; output?: number }
  cost?: { input?: number; output?: number }
}

interface UpstreamProvider {
  name?: string
  api?: string
  models?: Record<string, UpstreamModel>
}

function num(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined
}

async function main(): Promise<void> {
  console.log(`fetching ${SOURCE}`)
  const catalog = await fetch(SOURCE).then((r) => {
    if (!r.ok) throw new Error(`models.dev returned ${r.status}`)
    return r.json() as Promise<Record<string, UpstreamProvider>>
  })

  const upstreamCount = Object.values(catalog)
    .reduce((total, p) => total + Object.keys(p.models ?? {}).length, 0)
  console.log(`  ${Object.keys(catalog).length} providers, ${upstreamCount} models upstream`)

  const out: Record<string, unknown[]> = {}
  let kept = 0
  const missing: string[] = []

  for (const [ours, theirs] of Object.entries(CATALOG_PROVIDERS)) {
    const provider = catalog[theirs]
    if (!provider?.models) {
      missing.push(`${ours} (looked for "${theirs}")`)
      continue
    }
    const models = Object.entries(provider.models)
      .map(([id, m]) => ({
        id: m.id ?? id,
        name: m.name ?? id,
        context: num(m.limit?.context),
        maxOutput: num(m.limit?.output),
        inputCost: num(m.cost?.input),
        outputCost: num(m.cost?.output),
        tools: m.tool_call === true || undefined,
        reasoning: m.reasoning === true || undefined,
        vision: (m.modalities?.input ?? []).includes('image') || undefined,
        released: m.release_date,
      }))
      // Newest first — the model someone wants is far more often recent than
      // alphabetically early, and a picker over 40 entries needs a useful order.
      .sort((a, b) => (b.released ?? '').localeCompare(a.released ?? '') || a.id.localeCompare(b.id))

    out[ours] = models
    kept += models.length
  }

  if (missing.length) {
    console.error(`\nFATAL: no upstream entry for: ${missing.join(', ')}`)
    console.error('models.dev renamed or dropped a provider — fix CATALOG_PROVIDERS.')
    process.exit(1)
  }

  const body = `// GENERATED by scripts/sync-model-catalog.ts — do not edit by hand.
//
// Source: ${SOURCE} (MIT, anomalyco/models.dev)
// Generated: ${new Date().toISOString().slice(0, 10)}
// ${Object.keys(out).length} providers, ${kept} models.
//
// Committed on purpose: a build must not depend on models.dev being reachable,
// and the settings page must render with no network at all. Re-run the script
// to refresh.

import type { CatalogModel } from './types'

export const MODEL_CATALOG: Readonly<Record<string, readonly CatalogModel[]>> = ${
    JSON.stringify(out, null, 0)
  } as const
`

  writeFileSync(OUT, body)
  const kb = (Buffer.byteLength(body) / 1024).toFixed(0)
  console.log(`\nwrote ${OUT} — ${Object.keys(out).length} providers, ${kept} models, ${kb} KB`)
}

main().catch((error) => {
  console.error('THREW', error)
  process.exit(1)
})
